### ISSUE TITLE
fatal error on Mar 2020 upgrade 

### ISSUE THREAD

**Issue by philbarker** [philbarker/omniana2#1]
Fatal error: Uncaught Error: Call to undefined function Pressbooks\Book\Helpers\display_menu() in /var/www/books/wp-content/themes/omniana2/header.php:82 Stack trace: #0 /var/www/books/wp-includes/template.php(722): require_once() #1 /var/www/books/wp-includes/template.php(671): load_template('/var/www/books/...', true) #2 /var/www/books/wp-includes/general-template.php(41): locate_template(Array, true) #3 /var/www/books/wp-content/themes/pressbooks-book/page-cover.php(6): get_header() #4 /var/www/books/wp-includes/template-loader.php(98): include('/var/www/books/...') #5 /var/www/books/wp-blog-header.php(19): require_once('/var/www/books/...') #6 /var/www/books/index.php(17): require('/var/www/books/...') #7 {main} thrown in /var/www/books/wp-content/themes/omniana2/header.php on line 82

**Comment by philbarker** [comment]
fixed, no longer have modified header.php
